# Generated by Django 5.2.17 on 2026-10-06 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('COMPLIANCE_MATRIX', 'Compliance Matrix'), ('BID_CHECKLIST', '입찰 체크리스트'), ('TECHNICAL_QUERY', '발주처 기술질의서'), ('REVIEW_REPORT', '검토 보고서')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('content', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', '초안'), ('FINAL', '확정')], default='DRAFT', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('generated_by', models.CharField(choices=[('AUTO', '자동 생성'), ('MANUAL', '직접 작성')], default='AUTO', max_length=10)),
                ('is_modified', models.BooleanField(default=False)),
                ('used_llm', models.BooleanField(default=False)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='bids.bidnotice')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bid_id', 'doc_type', '-version'],
                'constraints': [models.UniqueConstraint(fields=('bid', 'doc_type', 'version'), name='unique_draft_version')],
            },
        ),
    ]
