# Generated by Django 5.2.17 on 2026-10-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('value_type', models.CharField(choices=[('int', '정수'), ('float', '실수'), ('bool', '참/거짓'), ('str', '문자열'), ('json', 'JSON')], max_length=10)),
                ('group', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
    ]
