# Generated by Django 5.2.17 on 2026-10-05 15:04

import apps.llm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('OPENAI', 'ChatGPT (OpenAI)'), ('ANTHROPIC', 'Claude (Anthropic)'), ('GEMINI', 'Gemini (Google)')], max_length=20, unique=True)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('api_key_last4', models.CharField(blank=True, max_length=4)),
                ('base_url', models.CharField(blank=True, max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verify_ok', models.BooleanField(null=True)),
                ('last_verify_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='LLMModelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('OPENAI', 'ChatGPT (OpenAI)'), ('ANTHROPIC', 'Claude (Anthropic)'), ('GEMINI', 'Gemini (Google)')], max_length=20)),
                ('model_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('supports_pdf_input', models.BooleanField(default=False)),
                ('max_output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['provider', 'order', 'model_id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'model_id'), name='uniq_provider_model')],
            },
        ),
        migrations.CreateModel(
            name='LLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_provider', models.CharField(choices=[('OPENAI', 'ChatGPT (OpenAI)'), ('ANTHROPIC', 'Claude (Anthropic)'), ('GEMINI', 'Gemini (Google)')], default='ANTHROPIC', max_length=20)),
                ('temperature', models.FloatField(default=0.2)),
                ('max_output_tokens', models.PositiveIntegerField(default=8192)),
                ('timeout_sec', models.PositiveIntegerField(default=180)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('json_mode', models.BooleanField(default=True)),
                ('per_task_overrides', models.JSONField(blank=True, default=apps.llm.models.default_task_overrides)),
                ('active_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='llm.llmmodeloption')),
            ],
            options={
                'verbose_name': 'LLM settings',
            },
        ),
    ]
