# Generated by Django 5.2.17 on 2026-10-05 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job'),
        ('llm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField()),
                ('output_schema', models.JSONField(blank=True, null=True)),
                ('version', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', '-version'],
            },
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.CharField(db_index=True, max_length=100)),
                ('provider', models.CharField(choices=[('OPENAI', 'ChatGPT (OpenAI)'), ('ANTHROPIC', 'Claude (Anthropic)'), ('GEMINI', 'Gemini (Google)')], max_length=20)),
                ('model_id', models.CharField(max_length=100)),
                ('prompt_version', models.PositiveIntegerField(blank=True, null=True)),
                ('request_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('response_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OK', '성공'), ('ERROR', '오류'), ('INVALID_JSON', '형식 오류')], max_length=20)),
                ('error', models.TextField(blank=True)),
                ('request_excerpt', models.TextField(blank=True)),
                ('response_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.job')),
                ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='llm.prompttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='uniq_prompt_key_version'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('key',), name='uniq_active_prompt'),
        ),
    ]
