"""Seed document categories and their metadata fields (specs/02 §3, specs/06 §3–4).

Admins can edit all of this in the UI; seeding never overwrites existing rows.
"""

from .models import MetadataSchema


def F(key, label, type="str", unit="", required=False, description="", example=""):  # noqa: N802
    field = {"key": key, "label": label, "type": type, "required": required}
    if unit:
        field["unit"] = unit
    if description:
        field["description"] = description
    if example:
        field["example"] = example
    return field


SCHEMAS = [
    # ---- Company documents -------------------------------------------------------------
    {
        "code": "datasheet",
        "name": "제품 기술사양서",
        "owner_type": "COMPANY",
        "priority": 10,
        "target_model": "company.Product",
        "description": "필터 제품의 형식, 치수, 여재, 풍량, 차압, 등급 등 사양을 정리한 문서",
        "filename_patterns": [r"기술\s*사양서", r"data\s*sheet", r"TDS"],
        "fields": [
            F("model_no", "모델명", required=True, example="FT-VB500"),
            F("product_name", "제품명"),
            F("filter_type", "형식(분류)", description="PANEL/POCKET_BAG/V_BANK/..."),
            F("application", "주 용도"),
            F("dimension", "외형 치수", "dimension", "mm"),
            F("media", "여재"),
            F("frame_material", "프레임 재질"),
            F("frame_options", "프레임 옵션", "list"),
            F("gasket", "개스킷"),
            F("rated_airflow_m3h", "정격 풍량", "float", "m3/h"),
            F("initial_dp_pa", "초기 차압", "float", "Pa"),
            F("final_dp_pa", "권장 최종 차압", "float", "Pa"),
            F("airflow_dp_curve", "풍량-초기차압 특성", "list"),
            F("iso16890_class", "ISO 16890 등급"),
            F("iso29461_class", "ISO 29461-1 등급"),
            F("en1822_class", "EN 1822 등급"),
            F("en779_class", "EN 779 등급", description="관련 시험성적서 기준"),
            F("max_temp_c", "최고 사용 온도", "float", "°C"),
            F("max_rh", "최대 사용 습도", "float", "%RH"),
            F("fire_rating", "난연"),
            F("related_test_reports", "관련 시험성적서", "list"),
            F("revision", "개정"),
        ],
    },
    {
        "code": "test_report",
        "name": "시험성적서",
        "owner_type": "COMPANY",
        "priority": 20,
        "target_model": "company.TestReport",
        "description": "공인 시험기관이 발행한 필터 성능/난연 시험 결과 문서",
        "filename_patterns": [r"시험\s*성적서", r"test\s*report", r"^AFT-"],
        "fields": [
            F("report_no", "성적서 번호", required=True, example="AFT-2025-0402"),
            F("client", "의뢰자"),
            F("sample_name", "시료명"),
            F("model_no", "모델명"),
            F("sample_dimension", "시료 치수", "dimension", "mm"),
            F("standard", "시험 규격"),
            F("test_date", "시험 일자", "date"),
            F("issue_date", "발행 일자", "date"),
            F("lab_name", "시험 기관"),
            F("lab_accreditation", "인정 현황"),
            F("result_class", "판정 결과"),
            F("test_airflow_m3h", "시험 풍량", "float", "m3/h"),
            F("test_aerosol", "시험 에어로졸"),
            F("conditioning", "컨디셔닝"),
            F("initial_dp_pa", "초기 차압", "float", "Pa"),
            F("efficiency_by_size", "입경별 효율", "list"),
            F("epm1", "ePM1", "float", "%"),
            F("epm2_5", "ePM2.5", "float", "%"),
            F("epm10", "ePM10", "float", "%"),
            F("coarse", "ISO Coarse", "float", "%"),
            F("mpps_um", "MPPS", "float", "µm"),
            F("integral_eff", "MPPS 전체 효율", "float", "%"),
            F("local_eff", "국부 효율"),
            F("leak_test", "누설 시험"),
            F("dust_holding_g", "분진 보유량", "float", "g"),
            F("eff_0_4um_initial", "0.4µm 초기 효율", "float", "%"),
            F("eff_0_4um_conditioned", "0.4µm 컨디셔닝 후 효율", "float", "%"),
            F("results", "시험 결과(전체)", "json"),
            F("conditions", "시험 조건(전체)", "json"),
            F("notes", "비고"),
        ],
    },
    {
        "code": "certificate",
        "name": "인증서/확인서",
        "owner_type": "COMPANY",
        "priority": 30,
        "target_model": "company.Certificate",
        "description": "ISO 인증서, 직접생산확인증명서, 중소기업확인서 등 회사 인증·자격 문서",
        "filename_patterns": [r"인증서", r"증명서", r"확인서", r"certificate"],
        "fields": [
            F("cert_no", "인증 번호", required=True),
            F("cert_name", "인증명"),
            F("standard", "규격"),
            F("holder", "인증 대상"),
            F("scope", "인증 범위"),
            F("product_codes", "세부품명번호", "list"),
            F("issue_date", "최초/갱신 인증일", "date"),
            F("valid_from", "유효 시작일", "date"),
            F("valid_until", "유효 종료일", "date"),
            F("issuer", "발급 기관"),
        ],
    },
    {
        "code": "delivery_record",
        "name": "납품실적",
        "owner_type": "COMPANY",
        "priority": 40,
        "target_model": "company.DeliveryRecord",
        "description": "발주처·사업명·모델·수량 등 과거 납품 실적 목록",
        "filename_patterns": [r"납품\s*실적", r"실적\s*(목록|증명)"],
        "fields": [
            F("as_of", "기준 시점"),
            F("records", "실적 목록", "list", required=True),
        ],
    },
    {
        "code": "company_profile",
        "name": "회사 소개/정보",
        "owner_type": "COMPANY",
        "priority": 50,
        "target_model": "company.Company",
        "description": "회사 개요, 사업자 정보, 연락처, 주요 제품을 담은 문서",
        "filename_patterns": [r"회사\s*(소개|개요|정보)", r"company\s*profile"],
        "fields": [
            F("name", "회사명"),
            F("ceo", "대표자"),
            F("business_no", "사업자번호"),
            F("address", "주소"),
            F("phone", "연락처"),
            F("email", "이메일"),
            F("is_sme", "중소기업 여부", "bool"),
            F("g2b_items", "나라장터 등록 물품", "list"),
            F("main_products", "주요 제품"),
        ],
    },
    # ---- Bid attachments (specific categories first) ------------------------------------
    {
        "code": "bid_restriction_reason",
        "name": "제한경쟁사유서",
        "owner_type": "BID",
        "priority": 110,
        "target_model": "bids.BidRequirement",
        "description": "제한경쟁 입찰의 사유와 실적·자격 제한 내용을 설명하는 문서",
        "filename_patterns": [r"제한\s*경쟁\s*사유"],
        "fields": [
            F("restriction_type", "제한 유형"),
            F("track_record_requirement", "실적 요건"),
            F("reason", "사유"),
        ],
    },
    {
        "code": "bid_evaluation_criteria",
        "name": "계약이행능력심사 세부기준",
        "owner_type": "BID",
        "priority": 120,
        "target_model": "bids.BidRequirement",
        "description": "적격심사·계약이행능력심사의 평가 항목과 배점 기준",
        "filename_patterns": [r"이행\s*능력\s*심사", r"세부\s*기준", r"적격\s*심사"],
        "fields": [F("criteria", "심사 항목", "list"), F("pass_score", "통과 점수", "float")],
    },
    {
        "code": "bid_contract_terms",
        "name": "물품구매계약 조건",
        "owner_type": "BID",
        "priority": 130,
        "target_model": "bids.BidRequirement",
        "description": "물품구매계약 일반조건·특수조건 (납기, 지체상금, 하자, 제출서류 등)",
        "filename_patterns": [r"계약.*조건", r"과업\s*(내용|지시)서"],
        "fields": [
            F("delivery_terms", "납기"),
            F("penalty", "지체상금"),
            F("warranty", "하자담보"),
            F("inspection", "검사"),
            F("required_documents", "제출서류", "list"),
        ],
    },
    {
        "code": "bid_drawing",
        "name": "도면",
        "owner_type": "BID",
        "priority": 140,
        "target_model": "bids.BidItem",
        "description": "품목의 형상과 치수를 보여주는 도면",
        "filename_patterns": [r"도면", r"drawing"],
        "fields": [F("items", "품목 치수", "list")],
    },
    {
        "code": "bid_item_list",
        "name": "물품명세서/구매내역서",
        "owner_type": "BID",
        "priority": 150,
        "target_model": "bids.BidItem",
        "description": "구매 품목, 규격, 단위, 수량을 나열한 명세서·내역서",
        "filename_patterns": [r"명세서", r"(구매|산출)\s*내역서", r"품목"],
        "fields": [F("items", "품목", "list", required=True)],
    },
    {
        "code": "bid_spec",
        "name": "규격서/시방서",
        "owner_type": "BID",
        "priority": 160,
        "target_model": "bids.BidRequirement",
        "description": "한난물자규격서, 구매규격서, 제조·구매 규격서, 시방서 등 기술 요구사항 문서",
        "filename_patterns": [r"규격서", r"시방서", r"(?<!기술)사양서", r"specification"],
        "fields": [
            F("spec_title", "규격서명"),
            F("issuing_dept", "작성 부서"),
            F("written_date", "작성 일자"),
            F("items", "품목", "list"),
            F("performance", "성능 요구", "list"),
            F("test_and_inspection", "시험 및 검사"),
            F("submission_docs", "제출서류", "list"),
            F("delivery_terms", "납기"),
            F("warranty", "하자보증"),
        ],
    },
    {
        "code": "bid_notice",
        "name": "입찰공고문",
        "owner_type": "BID",
        "priority": 170,
        "target_model": "bids.BidNotice",
        "description": "입찰 개요, 일정, 금액, 참가자격, 제출서류를 공고하는 문서",
        "filename_patterns": [r"공고문", r"공고서", r"입찰\s*공고", r"재입찰"],
        "fields": [
            F("notice_no", "입찰공고번호"),
            F("title", "공고명", required=True),
            F("buyer_org", "수요기관"),
            F("contracting_org", "계약기관"),
            F("contacts", "담당자", "json"),
            F("bid_method", "입찰 방법"),
            F("item_category_code", "세부품명번호"),
            F("item_category_name", "세부품명"),
            F("budget_krw", "사업금액", "int", "KRW"),
            F("estimated_price_krw", "추정가격", "int", "KRW"),
            F("bid_open_at", "입찰서 제출 시작", "date"),
            F("bid_close_at", "입찰서 제출 마감", "date"),
            F("opening_at", "개찰 일시", "date"),
            F("qualification_deadline_at", "자격서류 마감", "date"),
            F("delivery_terms", "납품기한"),
            F("delivery_place", "납품장소"),
            F("warranty_terms", "하자담보"),
            F("split_delivery", "분할납품", "bool"),
            F("qualifications", "입찰참가자격", "list"),
            F("required_documents", "제출서류", "list"),
        ],
    },
    {
        "code": "bid_other",
        "name": "기타 첨부",
        "owner_type": "BID",
        "priority": 999,
        "target_model": "",
        "description": "위 분류에 해당하지 않는 입찰 첨부",
        "filename_patterns": [],
        "fields": [],
    },
]


def seed_metadata_schemas() -> int:
    existing = set(MetadataSchema.objects.values_list("code", flat=True))
    created = [MetadataSchema(**schema) for schema in SCHEMAS if schema["code"] not in existing]
    MetadataSchema.objects.bulk_create(created)
    return len(created)
