import { FILTER_TYPES } from '@/utils/options'

// Product form fields (specs/02 §4 Product).
export const PRODUCT_FIELDS = [
  { key: 'model_no', label: '모델명', required: true, col: 'col-md-4' },
  { key: 'name', label: '제품명', col: 'col-md-5' },
  {
    key: 'filter_type',
    label: '형식',
    type: 'select',
    options: FILTER_TYPES,
    required: true,
    col: 'col-md-3',
  },
  { key: 'application', label: '용도', col: 'col-12' },
  { key: 'width_mm', label: '폭 W', type: 'number', unit: 'mm', col: 'col-md-2' },
  { key: 'height_mm', label: '높이 H', type: 'number', unit: 'mm', col: 'col-md-2' },
  { key: 'depth_mm', label: '깊이 D', type: 'number', unit: 'mm', col: 'col-md-2' },
  { key: 'diameter_mm', label: '지름', type: 'number', unit: 'mm', col: 'col-md-2' },
  { key: 'diameter2_mm', label: '지름2(원추)', type: 'number', unit: 'mm', col: 'col-md-2' },
  { key: 'length_mm', label: '길이', type: 'number', unit: 'mm', col: 'col-md-2' },
  { key: 'dimension_text', label: '치수 원문', col: 'col-md-6' },
  { key: 'media', label: '여재', col: 'col-md-6' },
  { key: 'frame_material', label: '프레임', col: 'col-md-6' },
  { key: 'gasket', label: '개스킷', col: 'col-md-6' },
  { key: 'rated_airflow_m3h', label: '정격 풍량', type: 'number', unit: 'm³/h', col: 'col-md-4' },
  { key: 'initial_dp_pa', label: '초기 차압', type: 'number', unit: 'Pa', col: 'col-md-4' },
  { key: 'final_dp_pa', label: '권장 최종 차압', type: 'number', unit: 'Pa', col: 'col-md-4' },
  { key: 'iso16890_class', label: 'ISO 16890 등급', col: 'col-md-3' },
  { key: 'iso29461_class', label: 'ISO 29461-1 등급', col: 'col-md-3' },
  { key: 'en1822_class', label: 'EN 1822 등급', col: 'col-md-2' },
  { key: 'en779_class', label: 'EN 779 등급', col: 'col-md-2' },
  { key: 'ashrae_merv', label: 'MERV', type: 'number', col: 'col-md-2' },
  { key: 'max_temp_c', label: '최고 온도', type: 'number', unit: '°C', col: 'col-md-3' },
  { key: 'max_rh', label: '최대 습도', type: 'number', unit: '%RH', col: 'col-md-3' },
  { key: 'fire_rating', label: '난연', col: 'col-md-6' },
  { key: 'revision', label: '개정', col: 'col-md-3' },
  { key: 'is_active', label: '판매 중', type: 'checkbox', col: 'col-md-3' },
  {
    key: 'airflow_dp_curve',
    label: '풍량-초기차압 특성',
    type: 'json',
    empty: [],
    col: 'col-md-6',
    help: '[{"airflow_m3h": 3400, "dp_pa": 102}, ...]',
  },
  {
    key: 'frame_options',
    label: '프레임 옵션',
    type: 'json',
    empty: [],
    col: 'col-md-6',
    help: '[{"material": "SUS304", "model": "FT-EP700S", "note": "주문제작"}]',
  },
  {
    key: 'dimension_variants',
    label: '제작 가능 치수/옵션',
    type: 'json',
    empty: [],
    col: 'col-md-6',
  },
  { key: 'extra', label: '기타 메타데이터', type: 'json', empty: {}, col: 'col-md-6' },
]
