# Generated by Django 5.2.17 on 2026-10-05 15:27

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('owner_type', models.CharField(choices=[('COMPANY', '회사 자료'), ('BID', '입찰 첨부')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('filename_patterns', models.JSONField(blank=True, default=list)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['owner_type', 'priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, upload_to=apps.documents.models.document_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_format', models.CharField(choices=[('TXT', 'Txt'), ('DOCX', 'Docx'), ('DOC', 'Doc'), ('HWP', 'Hwp'), ('HWPX', 'Hwpx'), ('PDF', 'Pdf'), ('XLS', 'Xls'), ('XLSX', 'Xlsx')], max_length=10)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_text', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_tables', models.JSONField(blank=True, default=list)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('category_confidence', models.FloatField(blank=True, null=True)),
                ('category_source', models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동')], default='AUTO', max_length=10)),
                ('status', models.CharField(choices=[('UPLOADED', '업로드됨'), ('PARSING', '텍스트 추출 중'), ('PARSED', '텍스트 추출됨'), ('NEEDS_OCR', 'OCR 필요'), ('EXTRACTING', '메타데이터 추출 중'), ('EXTRACTED', '추출 완료'), ('REVIEWED', '검토 완료'), ('FAILED', '실패')], default='UPLOADED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('owner_type', models.CharField(choices=[('COMPANY', '회사 자료'), ('BID', '입찰 첨부')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.metadataschema')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('value', models.JSONField(blank=True, null=True)),
                ('raw_value', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(choices=[('RULE', '규칙'), ('LLM', 'LLM'), ('MANUAL', '수동')], default='RULE', max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence_page', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_quote', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document', 'id'],
                'constraints': [models.UniqueConstraint(fields=('document', 'key'), name='uniq_document_metadata_key')],
            },
        ),
    ]
