# Generated by Django 5.2.17 on 2026-10-06 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_attachment', to='documents.document')),
            ],
            options={
                'ordering': ['bid', '-is_primary', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BidNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_no', models.CharField(blank=True, db_index=True, max_length=50)),
                ('source_ref', models.CharField(blank=True, db_index=True, max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('buyer_org', models.CharField(blank=True, max_length=200)),
                ('contracting_org', models.CharField(blank=True, max_length=200)),
                ('buyer_contact', models.JSONField(blank=True, default=dict)),
                ('contract_contact', models.JSONField(blank=True, default=dict)),
                ('plant_name', models.CharField(blank=True, max_length=200)),
                ('is_power_plant', models.BooleanField(null=True)),
                ('bid_method', models.CharField(blank=True, max_length=200)),
                ('procurement_type', models.CharField(blank=True, max_length=50)),
                ('item_category_code', models.CharField(blank=True, max_length=30)),
                ('item_category_name', models.CharField(blank=True, max_length=100)),
                ('budget_krw', models.BigIntegerField(blank=True, null=True)),
                ('estimated_price_krw', models.BigIntegerField(blank=True, null=True)),
                ('bid_open_at', models.DateTimeField(blank=True, null=True)),
                ('bid_close_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('opening_at', models.DateTimeField(blank=True, null=True)),
                ('qualification_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_terms', models.CharField(blank=True, max_length=300)),
                ('delivery_place', models.CharField(blank=True, max_length=300)),
                ('warranty_terms', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('fit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fit_reason', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('PENDING', '진행 중'), ('WON', '낙찰'), ('LOST', '미낙찰'), ('NOT_BID', '불참')], default='PENDING', max_length=10)),
                ('review_status', models.CharField(choices=[('UNREVIEWED', '미확인'), ('REVIEWED', '확인')], default='UNREVIEWED', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('DRAFT', '등록됨'), ('EXTRACTING', '추출 중'), ('EXTRACTED', '추출 완료'), ('EVALUATING', '판정 중'), ('EVALUATED', '판정 완료'), ('FAILED', '실패')], default='DRAFT', max_length=12)),
                ('processing_error', models.TextField(blank=True)),
                ('source_text', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_no', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=300)),
                ('spec_text', models.TextField(blank=True)),
                ('filter_type', models.CharField(blank=True, choices=[('PANEL', '패널형'), ('POCKET_BAG', '포켓/백필터'), ('V_BANK', 'V-bank'), ('MINI_PLEAT_HEPA', '미니플리트/HEPA'), ('CARTRIDGE_PULSE', '펄스 카트리지'), ('DEMISTER', '데미스터'), ('CARBON', '카본(활성탄)'), ('OTHER', '기타')], max_length=20)),
                ('width_mm', models.FloatField(blank=True, null=True)),
                ('height_mm', models.FloatField(blank=True, null=True)),
                ('depth_mm', models.FloatField(blank=True, null=True)),
                ('depth_mm_max', models.FloatField(blank=True, null=True)),
                ('diameter_mm', models.FloatField(blank=True, null=True)),
                ('diameter2_mm', models.FloatField(blank=True, null=True)),
                ('length_mm', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('material_no', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.product')),
                ('source_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bids.bidattachment')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bids.bidnotice')),
            ],
            options={
                'ordering': ['bid', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bidattachment',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bids.bidnotice'),
        ),
        migrations.CreateModel(
            name='BidRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('DIMENSION', '제품 치수'), ('FILTER_TYPE', '필터 형식'), ('FILTER_GRADE', '필터 등급'), ('EFFICIENCY', '효율'), ('PRESSURE_DROP', '차압'), ('AIRFLOW', '풍량'), ('MATERIAL', '재질'), ('ENVIRONMENT', '사용 환경'), ('FIRE_RATING', '난연'), ('TEST_STANDARD', '시험 규격'), ('CERTIFICATION', '인증·자격'), ('TRACK_RECORD', '납품실적'), ('DELIVERY', '납기'), ('SUBMISSION_DOC', '제출서류'), ('WARRANTY', '하자보증'), ('INSPECTION', '시험·검사'), ('OTHER', '기타')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('requirement_text', models.TextField(blank=True)),
                ('normalized', models.JSONField(blank=True, default=dict)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_quote', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('LLM', 'LLM'), ('RULE', '규칙'), ('MANUAL', '수동')], default='LLM', max_length=10)),
                ('is_locked', models.BooleanField(default=False)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='bids.bidnotice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='bids.biditem')),
                ('source_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bids.bidattachment')),
            ],
            options={
                'ordering': ['bid', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BidProductMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('reason', models.TextField(blank=True)),
                ('rank', models.PositiveSmallIntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='bids.bidnotice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='bids.biditem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company.product')),
            ],
            options={
                'ordering': ['item', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('item', 'product'), name='uniq_item_product_match')],
            },
        ),
    ]
